### ISSUE TITLE
Spring Guides Building a Gateway filters: add Request header --> add Response header

### ISSUE THREAD

**Issue by avi613** [spring-guides/gs-gateway#1]
Dear all @Spring,

I'm running through the [GS Gateway](https://spring.io/guides/gs/gateway/) and have noticed what seems to be a small typo in the following snippet:

```
@Bean
public RouteLocator myRoutes(RouteLocatorBuilder builder) {
    return builder.routes()
        .route(p -> p
            .path("/get")
            .filters(f -> f.addRequestHeader("Hello", "World"))
            .uri("http://httpbin.org:80"))
        .build();
}
```

If you wish to modify the response header, then instead of

```
            .filters(f -> f.addRequestHeader("Hello", "World"))
```
there should be
```
            .filters(f -> f.addResponseHeader("Hello", "World"))
```

**Response** instead of **Request**.

**Comment by gregturn** [comment]
But the prose says "In our configuration of this route we will add a filter that will add the request header Hello with the value World to the request before it is routed", indicating that the purpose is to set a **request header**.

**Comment by ryanjbaxter** [comment]
Right we did not want to add a response header we wanted to add a request header.  HTTPBin will return in the response the headers that were in the request sent to it.

**Comment by avi613** [comment]
OK, I got it!

The fact is that I haven't been able to run the tuto with httpbin because of some restrictions of the company where I work. But I got the idea.
