### ISSUE TITLE
has anyone got an 404 error？

### ISSUE THREAD

**Issue by xiaoxiaoliner** [spring-guides/gs-gateway#2]
i'm trying to use Hystrix, 
but when i visit "http://localhost:8080/delay/3" ,i got a 404 error.
 it seems like the "host: www.hystrix.com" setting no effect.
Has anyone encountered this situation?

**Comment by ryanjbaxter** [comment]
Have you tried running the complete sample code from the `complete` folder?  Does that work?

**Comment by lradziwonowicz** [comment]
@ryanjbaxter I just checked it, it works, but the application is running on port `9999`.

For anyone wondering why it only works with `/delay` endpoint, it is part of httpbin: [https://httpbin.org/#/Dynamic_data/get_delay__delay_](https://httpbin.org/#/Dynamic_data/get_delay__delay_)
