### ISSUE TITLE
Update Spring Boot to the latest version

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-gateway#21]
Update the guide to use the most recent Spring Boot version.

Files that require changes are:

```
initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml
```

**Comment by ali-so** [comment]
It seems that RouteLocator is removed!

**Comment by robertmcnees** [comment]
Hi @ali-so. Based on the time of your content (that is, after the Boot 3.2 release in November 2023), the guide was likely asking you to pull in the wrong dependency. Our Guide asked the user to start a new project on Spring Initializr by pulling in `Gateway`. That dependency now pulls in `spring-cloud-starter-gateway-mvc`. This guide was written for the reactive version of Gateway, specifically the dependency `spring-cloud-starter-gateway` is required (no `-mvc`). You can preserve the previous functionality by specifying `Reactive Gateway` in the dependency list on Spring Initializr. Recent PRs #22 and #23 should address this issue going forward. If you feel there is still an issue with the guide please open a new issue.

Regarding the initial issue, I'm closing this issue in favor of a new way to track dependency updates on a higher level.
